name: Neutron
version: 2.0
main: com.example.Neutron
api-version: 1.21
description: This is a Gemini API integration plugin
commands:
    ai:
        description: Use the AI
        usage: /ai <text>
    aireload:
        description: reload Neutron config
        usage: /aireload
permissions:
  neutron.reload:
      default: op